hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: "gelu"
layer_norm_eps: 1e-12
initializer_range: 0.02
mask_ratio: 0.2
aap_weight: 1.0
mip_weight: 0.2
map_weight: 1.0
sp_weight: 0.5
epochs: 18
pretrain_epochs: 2
save_step: 2
