hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: "gelu"
layer_norm_eps: 1e-12
initializer_range: 0.02

lmd: 0.1
lmd_sem: 0.1
global_ratio: 1
dual_domain: False
std: False
fredom: False
spatial_ratio: 0.
topk_factor: 1
